SachOnline/Areas/Admin/Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace SachOnline.Areas.Admin.Controllers
{
    public class ChuDeController : Controller
    {
        dbSachOnlineDataContext db = new dbSachOnlineDataContext();


        public ActionResult Index(int? page)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")

            {
                return RedirectToAction("Login", "Home");

            }
            else

            {
                ADMIN kh = (ADMIN)Session["Admin"];
                var sach = db.ADMINs.SingleOrDefault(n => n.Quyen == kh.Quyen);
                if (sach.Quyen == 1)
                {
                    int iPageNum = (page ?? 1);
                    int iPageSize = 10;
                    return View(db.Categories.ToList().OrderBy(n => n.CategoryID).ToPagedList(iPageNum, iPageSize));
                }
                return RedirectToAction("Quyenthaotac", "Home");

            }
            
        }
        [HttpGet]
        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Category category, FormCollection f)
        {
            
            if (f["sCategoryName"] == null)
            {
                //Nội dung thông báo yêu cầu chọn ảnh bìa
                ViewBag.Thongbao = "Hãy nhập tên chủ đề";
                
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {


                    category.CategoryName = f["sCategoryName"];
                    db.Categories.InsertOnSubmit(category);
                    db.SubmitChanges();
                    //Về lại trang Quản lý sách
                    return RedirectToAction("Index");
                }
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            var sach = db.Categories.SingleOrDefault(n => n.CategoryID == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var chude = db.Categories.SingleOrDefault(n => n.CategoryID == id);
            if (chude == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(chude);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var chude = db.Categories.SingleOrDefault(n => n.CategoryID == id);
            if (chude == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Xóa sách
            db.Categories.DeleteOnSubmit(chude);
            db.SubmitChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var sach = db.Categories.SingleOrDefault(n => n.CategoryID == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Hiển thị danh sách chủ đề và nhà xuất bản đồng thời chọn chủ đề và nhà xuất bản của cuốn hiện tại
            ViewBag.CategoryID = new SelectList(db.Categories.ToList().OrderBy(n => n.CategoryName), "CategoryID", "CategoryName", sach.CategoryID);
            return View(sach);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f)
        {
            var sach = db.Categories.SingleOrDefault(n => n.CategoryID == int.Parse(f["iCategoryID"]));
           
            if (ModelState.IsValid)
            {
                

                //Lưu sách vào cơ sở dữ liệu
                sach.CategoryName = f["sCategoryName"];
                

                db.SubmitChanges();
                //Về lại trang Quản lý sách
                return RedirectToAction("Index");
            }
            return View(sach);
        }

    }
}

SachOnline/Areas/Admin/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace SachOnline.Areas.Admin.Controllers
{
    

    public class SachController : Controller
    {
        
        // GET: Admin/Sach

        dbSachOnlineDataContext db = new dbSachOnlineDataContext();

        
        public ActionResult Index(int ? page)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")

            {
                return RedirectToAction("Login", "Home");

            }
            else

            {
                ADMIN admina = (ADMIN)Session["Admin"];
                var sach = db.ADMINs.SingleOrDefault(n => n.Quyen == admina.Quyen);
                if (sach.Quyen == 1)
                {
                    int iPageNum = (page ?? 1);
                    int iPageSize = 7;
                    return View(db.Books.ToList().OrderBy(n => n.BookID).ToPagedList(iPageNum, iPageSize));
                }
                return RedirectToAction("Quyenthaotac", "Home");

            }
           
        }
        [HttpGet]
        public ActionResult Create()
        {
            //Lấy ds từ các table ChuDe, NhaXuatBan, Hiển thị tên, khi chọn sẽ lấy mã
            ViewBag.CategoryID = new SelectList(db.Categories.ToList().OrderBy(n => n.CategoryName), "CategoryID", "CategoryName");
            ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.NhaXuatBanName), "NhaXuatBanID", "NhaXuatBanName");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Book sach, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            //Ðưa dữ liệu vào DropDown
            ViewBag.CategoryID = new SelectList(db.Categories.ToList().OrderBy(n => n.CategoryName), "CategoryID", "CategoryName");
            ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.NhaXuatBanName), "NhaXuatBanID", "NhaXuatBanName");
            if (fFileUpload == null)
            {
                //Nội dung thông báo yêu cầu chọn ảnh bìa
                ViewBag.Thongbao = "Hãy chọn ảnh bìa";
                //Lưu thông tin để khi load lại trang do yêu cầu chọn ảnh bìa sẽ hiển thị các thông tin này lên trang 
                ViewBag.TenSach = f["sTenSach"];
                ViewBag.Description = f["sDescription"];
                ViewBag.ViewCount = int.Parse(f["iViewCount"]);
                ViewBag.Price = decimal.Parse(f["mPrice"]);
                ViewBag.CategoryID = new SelectList(db.Categories.ToList().OrderBy(n => n.CategoryName), "CategoryID", "CategoryName", int.Parse(f["CategoryID"]));
                ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.NhaXuatBanName), "NhaXuatBanID", "NhaXuatBanName", int.Parse(f["NhaXuatBanID"]));
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                //Lấy tên file(Khai báo thư viện: System.IO)
                  var sFileName = Path.GetFileName(fFileUpload.FileName);
 
                 //Lấy đường dẫn lưu file
                 var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                 //Kiểm tra ảnh bìa đã tồn taji chưa để lưu lên thư mục
                 if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    //Lưu Sach vào csdl

                    sach.Title = f["sTenSach"];
                    sach.Description = f["sDescription"];
                    sach.Images = sFileName;
                    sach.Published = Convert.ToDateTime(f["dPublished"]);
                    sach.ViewCount = int.Parse(f["iViewCount"]);
                    sach.Price = decimal.Parse(f["mPrice"]);
                    sach.CategoryID = int.Parse(f["CategoryID"]);
                    sach.NhaXuatBanID = int.Parse(f["NhaXuatBanID"]);
                    db.Books.InsertOnSubmit(sach);
                    db.SubmitChanges();
                    //Về lại trang Quản lý sách
                    return RedirectToAction("Index");
                }
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            var sach = db.Books.SingleOrDefault(n => n.BookID == id);
            if(sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var sach = db.Books.SingleOrDefault(n => n.BookID == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var sach = db.Books.SingleOrDefault(n => n.BookID == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var ctdh = db.CHITIETDATHANGs.Where(ct => ct.BookID == id);
            if (ctdh.Count() > 0)
            {
                //Nội dung sẽ hiển thị khi sách cần xóa đã có trong table CHITIETDATHANG
                ViewBag.ThongBao = "Sách này đang có trong bảng Chi tiết đặt hàng <br>" + "Nếu muốn xóa thì phải xóa hết mã sách này trong bảng chi tiết đặt hàng";
                return View(sach);
            }
            //Xóa hết thông tin của cuốn sách trong table VietSach trước khi xóa sách này
            var vietsach = db.VIETSACHes.Where(vs => vs.BookID == id).ToList();
            if (vietsach != null)
            {
                db.VIETSACHes.DeleteAllOnSubmit(vietsach);
                db.SubmitChanges();
            }
            //Xóa sách
            db.Books.DeleteOnSubmit(sach);
            db.SubmitChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var sach = db.Books.SingleOrDefault(n => n.BookID == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Hiển thị danh sách chủ đề và nhà xuất bản đồng thời chọn chủ đề và nhà xuất bản của cuốn hiện tại
            ViewBag.CategoryID = new SelectList(db.Categories.ToList().OrderBy(n => n.CategoryName), "CategoryID", "CategoryName", sach.CategoryID);
            ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.NhaXuatBanName), "NhaXuatBanID", "NhaXuatBanName", sach.NhaXuatBanID);
            return View(sach);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            var sach = db.Books.SingleOrDefault(n => n.BookID == int.Parse(f["iBookID"]));
            ViewBag.CategoryID = new SelectList(db.Categories.ToList().OrderBy(n => n.CategoryName), "CategoryID", "CategoryName",sach.CategoryID);
            ViewBag.NhaXuatBanID = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.NhaXuatBanName), "NhaXuatBanID", "NhaXuatBanName",sach.NhaXuatBanID);
            if (ModelState.IsValid)
            {
                if (fFileUpload != null)//Kiểm tra để xác nhận cho thay đổi ảnh bìa
                {
                    //Lấy tên file (Khai báo thư viện :System>IO)
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    //Lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    //Kiểm tra File đã tồn tại hay chưa
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    sach.Images = sFileName;
                }

                //Lưu sách vào cơ sở dữ liệu
                sach.Title = f["sTitle"];
                sach.Description = f["sDescription"];

                sach.Published = Convert.ToDateTime(f["dPublished"]);
                sach.ViewCount = int.Parse(f["iViewCount"]);
                sach.Price = decimal.Parse(f["mPrice"]);
                sach.CategoryID = int.Parse(f["CategoryID"]);
                sach.NhaXuatBanID = int.Parse(f["NhaXuatBanID"]);

                db.SubmitChanges();
                //Về lại trang Quản lý sách
                return RedirectToAction("Index");
            }
            return View(sach);
        }
    }
}

SachOnline/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>
    @*
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Scripts/js")
    <style type="text/css">
        .imgbook {
            transition: all 1s ease-in;
            width: 400px;
        }

            .imgbook:hover {
                transform: scale(0.9);
                cursor: pointer;
            }

        .imgsachbannhieu {
            width: 100px;
        }
    </style>

    <style>
        /* CSS inline cho header */
        header {
            background-color: #333;
            color: #fff;
            padding: 5px;
            text-align: center;
        }

        h1 {
            font-size: 36px;
        }

        nav li {
            display: inline; /* Hiển thị các mục menu trên cùng một hàng */
            margin-right: 20px; /* Khoảng cách giữa các mục menu */
            color: white;
        }

        nav a {
            text-decoration: none;
            color: #fff; /* Đổi màu chữ trong menu thành trắng */
            font-weight: bold;
        }

        /* Định dạng ô tìm kiếm */
        .search-box {
            display: inline-block;
            margin-left: 20px; /* Khoảng cách giữa ô tìm và menu */
        }

            .search-box input[type="text"] {
                padding: 5px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            .search-box button {
                padding: 5px 10px;
                background-color: #fff;
                color: #333;
                border: none;
                border-radius: 5px;
            }

        long-image {
            width: 300px;
            max-height: 50px; /* Điều chỉnh độ cao tối đa của hình ảnh */
            margin-top: 20px; /* Khoảng cách giữa header và hình ảnh */
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-inverse">

        <div class="container">

            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navAdmin" aria-expanded="false">

                <span class="icon-bar"></span> 
                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                </button>

        <a class="navbar-brand" href="@Url.Action("Index","Home")"> TRANG CHỦ</a> </div>

            <div class="collapse navbar-collapse" id="navAdmin">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Sach" )">QUẢN LÝ SẢN PHẨM </a> </li>



                    <li><a href="@Url.Action("Index","ChuDe")">QUẢN LÝ BỘ SƯU TẬP</a> </li>
                    <li><a href="@Url.Action("Index", "NhaXuatBan")">QUẢN LÝ LOẠI SẢN PHẨM</a> </li>
                    <li><a href="@Url.Action("Index", "KhachHang")">QUẢN LÝ KHÁCH HÀNG</a> </li>

                    <li><a href="@Url.Action("Index", "DonHang")">QUẢN LÝ ĐƠN HÀNG</a></li>
                    <li><a href="@Url.Action("Index", "Quyen")">QUẢN LÝ QUYỀN</a></li>
                    <li><a href="@Url.Action("Index", "Admin")">QUẢN LÝ NHÂN VIÊN VÀ CHỨC VỤ</a></li>
                    <li>@Html.Action("xinchao", "Home")</li>
                </ul>
            </div>

</div>

</nav>

        <div class="container">

                @RenderBody()

        </div>

<footer class="container well">
    <div style="text-align:center;">
        <p>ADMIN</p>
    </div>
</footer>

</body>
</html>

SachOnline/Areas/Admin/Views/Shared/_LayoutQuanTriVien.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>
    @*
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Scripts/js")
    <style type="text/css">
        .imgbook {
            transition: all 1s ease-in;
            width: 400px;
        }

            .imgbook:hover {
                transform: scale(0.9);
                cursor: pointer;
            }

        .imgsachbannhieu {
            width: 100px;
        }
    </style>

    <style>
        /* CSS inline cho header */
        header {
            background-color: #333;
            color: #fff;
            padding: 5px;
            text-align: center;
        }

        h1 {
            font-size: 36px;
        }

        nav li {
            display: inline; /* Hiển thị các mục menu trên cùng một hàng */
            margin-right: 20px; /* Khoảng cách giữa các mục menu */
            color: white;
        }

        nav a {
            text-decoration: none;
            color: #fff; /* Đổi màu chữ trong menu thành trắng */
            font-weight: bold;
        }

        /* Định dạng ô tìm kiếm */
        .search-box {
            display: inline-block;
            margin-left: 20px; /* Khoảng cách giữa ô tìm và menu */
        }

            .search-box input[type="text"] {
                padding: 5px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            .search-box button {
                padding: 5px 10px;
                background-color: #fff;
                color: #333;
                border: none;
                border-radius: 5px;
            }

        long-image {
            width: 300px;
            max-height: 50px; /* Điều chỉnh độ cao tối đa của hình ảnh */
            margin-top: 20px; /* Khoảng cách giữa header và hình ảnh */
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-inverse">

        <div class="container">

            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navAdmin" aria-expanded="false">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                    <span class="icon-bar"></span>

                </button>

                <a class="navbar-brand" href="@Url.Action("Index","Home")"> TRANG CHỦ</a>
            </div>

            <div class="collapse navbar-collapse" id="navAdmin">
                <ul class="nav navbar-nav">
                    @*<li><a href="@Url.Action("Index", "Sach" )">QUẢN LÝ SẢN PHẨM </a> </li>

            <li><a href="@Url.Action("Index", "Quyen")">QUẢN LÝ QUYỀN</a></li>
        <li><a href="@Url.Action("Index", "Admin")">QUẢN LÝ NHÂN VIÊN VÀ CHỨC VỤ</a></li>

        <li><a href="@Url.Action("Index","ChuDe")">QUẢN LÝ BỘ SƯU TẬP</a> </li>
        <li><a href="@Url.Action("Index", "NhaXuatBan")">QUẢN LÝ LOẠI SẢN PHẨM</a> </li>*@
                    <li><a href="@Url.Action("Index", "KhachHangQT")">QUẢN LÝ KHÁCH HÀNG</a> </li>

                    <li><a href="@Url.Action("Index", "DonHangQT")">QUẢN LÝ ĐƠN HÀNG</a></li>

                </ul>
            </div>

        </div>

    </nav>

    <div class="container">

        @RenderBody()

    </div>

    <footer class="container well">
        <div style="text-align:center;">
            <p>QUẢN TRỊ VIÊN</p>
        </div>
    </footer>

</body>
</html>