SachOnline/Controllers/SachOnlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using PagedList;
using PagedList.Mvc;

namespace SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        // GET: SachOnline
        //Tao đối tượng chứa csdl
        dbSachOnlineDataContext data = new dbSachOnlineDataContext();

        //Lấy ra sách cập nhật gần đây

            private List<Book> LaySachMoi(int count)
        {
            return data.Books.OrderByDescending(a => a.Published).Take(count).ToList();
        }
        private List<Book> LayProduct()
        {
            return data.Books.OrderByDescending(a => a.BookID).ToList();
        }
        public ActionResult Index( int ?page)
        {
            
            //return View(listSachMoi);
            
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int iSize = 8;
            //Tạo biến số trang
            int iPageNum = (page ?? 1);
            var listSachMoi = LaySachMoi(16);
            return View(listSachMoi.ToPagedList(iPageNum, iSize));
        }
        public ActionResult Product(int? page)
        {

            //return View(listSachMoi);

            //Tạo biến quy định số sản phẩm trên mỗi trang
            int iSize = 8;
            //Tạo biến số trang
            int iPageNum = (page ?? 1);
            var listSachMoi = LayProduct();
            return View(listSachMoi.ToPagedList(iPageNum, iSize));
        }

        
        public ActionResult ChuDePartial()
        {
            var listChuDe = from CategoryID in data.Categories select CategoryID;
            return PartialView(listChuDe);
        }
        
        public ActionResult _NhaXuatBanPartial()
        {

            var listNXB = from NhaXuatBanID in data.NhaXuatBans select NhaXuatBanID;
            return PartialView(listNXB);
        }
        public ActionResult SachTheoChuDe(int? iMaCD, int ? page)
        {
            // var sach = from s in data.Books where s.CategoryID == id select s;
            //return View(sach);
            ViewBag.CategoryID = iMaCD;
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int iSize = 3;
            //Tạo biến số trang
            int iPageNum = (page ?? 1);
            var sach = from s in data.Books where s.CategoryID == iMaCD select s;
            return View(sach.ToPagedList(iPageNum, iSize));
        }

        public ActionResult chudecss(int? iMaCD, int? page)
        {
            // var sach = from s in data.Books where s.CategoryID == id select s;
            //return View(sach);
            ViewBag.CategoryID = iMaCD;
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int iSize = 4;
            //Tạo biến số trang
            int iPageNum = (page ?? 1);
            var sach = from s in data.Books where s.CategoryID == iMaCD select s;
            return View(sach.ToPagedList(iPageNum, iSize));
        }

        public ActionResult SachTheoNhaXuatBan(int? iMaNXB, int ? page)
        {
            //var sach = from s in data.Books where s.NhaXuatBanID == id select s;
            //return View(sach);
            ViewBag.NhaXuatBanID = iMaNXB;
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int iSize = 3;
            //Tạo biến số trang
            int iPageNum = (page ?? 1);
            var sach = from s in data.Books where s.NhaXuatBanID == iMaNXB select s;
            return View(sach.ToPagedList(iPageNum, iSize));

        }
        public ActionResult NhaSanXuat(int? iMaNXB, int? page)
        {
            //var sach = from s in data.Books where s.NhaXuatBanID == id select s;
            //return View(sach);
            ViewBag.NhaXuatBanID = iMaNXB;
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int iSize = 4;
            //Tạo biến số trang
            int iPageNum = (page ?? 1);
            var sach = from s in data.Books where s.NhaXuatBanID == iMaNXB select s;
            return View(sach.ToPagedList(iPageNum, iSize));

        }
        private List<Book> LaySachBanNhieu(int count)
        {
            return data.Books.OrderByDescending(a => a.ViewCount).Take(count).ToList();
        }
        public ActionResult SachBanNhieuPartial()
        {
            var listSachBanNhieu = LaySachBanNhieu(4);
            return View(listSachBanNhieu);
        }
        public ActionResult ChiTietSach(int id)
        {
            var sach = from s in data.Books where s.BookID == id select s;
            return View(sach.Single());
        }
        public ActionResult LoginLogout()
        {
            return PartialView("LoginLogout");
        }
        public ActionResult About()
        {
            
            return View();
        }
        public ActionResult Contact()
        {

            return View();
        }
        public ActionResult Timkiem(string searchString, int? page)
        {
            int iSize = 8;
            //Tạo biến số trang
            int iPageNum = (page ?? 1);
            
            
            var links = from l in data.Books
                        select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                links = links.Where(s =>( s.Title.Contains(searchString))|| (s.Category.CategoryName.Contains(searchString)) || (s.NhaXuatBan.NhaXuatBanName.Contains(searchString)));
            }
            return View(links.ToPagedList(iPageNum, iSize));
            
        }
        public ActionResult Xem(int? page)
        {
            int iPageNum = (page ?? 1);
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

            {
                return Redirect("~/User/Dangnhap?id=3");

            }
            KHACHHANG kh = (KHACHHANG)Session["Taikhoan"];
            var links =
                         from l in data.CHITIETDATHANGs
                         join c in data.DONDATHANGs on l.MaDonHang equals c.MaDonHang

                         select c;
            var dem = links.Select(s => s.MaDonHang).Distinct().Count(); int iSize = dem;
            
            // if (!String.IsNullOrEmpty(TenKhachHang))
            //{
            links = links.Where(s => (s.KHACHHANG.Taikhoan == kh.Taikhoan)&&(s.KHACHHANG.Matkhau == kh.Matkhau));
            var demdon = links.Select(s => s.MaDonHang).Distinct().Count(); 
            ViewBag.DemDonHang = demdon;
            links = links.OrderByDescending(s => s.Ngaydat);
            return View(links.ToPagedList(iPageNum, iSize));
        }

        
        public ActionResult Xemlai(int? page)
        {

            int iPageNum = (page ?? 1);
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

            {
                return Redirect("~/User/Dangnhap?id=2");

            }
            KHACHHANG kh = (KHACHHANG)Session["Taikhoan"];
            var links =
                         from l in data.CHITIETDATHANGs
                         join c in data.DONDATHANGs on l.MaDonHang equals c.MaDonHang 

                         select c;
            var dem = links.Select(s => s.MaDonHang).Distinct().Count(); int iSize = dem;
            // if (!String.IsNullOrEmpty(TenKhachHang))
            //{
            links = links.Where(s => (s.KHACHHANG.Taikhoan == kh.Taikhoan) && (s.KHACHHANG.Matkhau == kh.Matkhau));
            links = links.OrderByDescending(s => s.Ngaydat);
            return View(links.ToPagedList(iPageNum, iSize));
        }
        public ActionResult Xemchitietcuadonhang(int id)
        {

            var order = data.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == id);

            if (order == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            // Fetch details for the specific order
            var orderDetails = (from ctdh in data.CHITIETDATHANGs
                                join ctdhdh in data.DONDATHANGs on ctdh.MaDonHang equals ctdhdh.MaDonHang
                                join kh in data.KHACHHANGs on ctdhdh.MaKH equals kh.MaKH
                                join ms in data.Books on ctdh.BookID equals ms.BookID
                                where ctdh.MaDonHang == id
                                select new donhang
                                {
                                    MaDonHang = ctdh.MaDonHang,
                                    MaKH = ctdhdh.MaKH,
                                    HoTen = kh.HoTen,
                                    Ngaydat = ctdhdh.Ngaydat,
                                    Ngaygiao = ctdhdh.Ngaygiao,
                                    Soluong = ctdh.Soluong,
                                    BookID = ms.BookID,
                                    Title = ms.Title,
                                    Dongia = ctdh.Dongia,
                                    
                                }).ToList();

            // Fetch customer name for the specific order
            var customerName = data.KHACHHANGs.Where(kh => kh.MaKH == order.MaKH).Select(kh => kh.HoTen).FirstOrDefault();

            // Pass the order, customer name, and order details to the view
            var viewModel = new OrderDetailsViewModel
            {
                Order = order,
                customerName = customerName,
                OrderDetails = orderDetails
            };

            return View(viewModel);
        }
        public ActionResult MuaLaiDonHang(int madon)
        {
            // Lấy thông tin đơn hàng cần mua lại
            var orderToBuy = data.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == madon);

            if (orderToBuy == null)
            {
                // Trả về trang lỗi 404 nếu không tìm thấy đơn hàng
                Response.StatusCode = 404;
                return null;
            }

SachOnline/Views/SachOnline/ChiTietSach.cshtml
@{
    ViewBag.Title = "ChiTietSach";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@*<style>
        .Title {
            font-size: 24px;
            font-weight: bold;
            margin-top: 10px;
        }

        /* Định dạng ảnh sách */
        /*img {
          //  max-width: 100%;
           // height: auto;
           // margin-top: 10px;
       // }*/

        /* Định dạng mô tả sách */
        .motasach {
            margin-top: 20px;
            font-size: 16px;
            line-height: 1.5;
            text-align: justify !important;

        }

        /* Định dạng ngày cập nhật */
        .ngaycapnhat {
            margin-top: 10px;
            font-weight: bold;
        }

        /* Định dạng giá bán */
        .giaban {
            margin-top: 10px;
            font-weight: bold;
            color: #e74c3c; /* Màu đỏ cho giá bán */
        }

        /* Định dạng nút Add to Cart */
        .addtocard {
            margin-top: 20px;
        }

        /* Định dạng nút mua sách */
        .btn-primary {
            background-color: #3498db; /* Màu xanh dương cho nút mua sách */
            border-color: #3498db;
            color: #fff;
            font-weight: bold;
        }

            .btn-primary:hover {
                background-color: #2980b9; /* Màu xanh dương nhạt khi hover */
                border-color: #2980b9;
            }
    </style>
    <h4 class="Title">
        @Model.Title
    </h4>
    <div class="text-center">
        <img src="~/Images/@Model.Images" alt="@Model.Title" />

        <div class="motasach" align="center">
            <p>
                @Html.Raw(Model.Description.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
            </p>
        </div>

        <p class="ngaycapnhat">Ngày cập nhật: @Html.FormatValue(@Model.Published, "{0:dd/MM/yyyy}")</p>
        <p class="giaban">Giá bán:<span>@Html.FormatValue(@Model.Price, "{0:#,##0}") VNĐ</span></p>
        <p class="addtocard">
            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = Model.BookID, url =Request.Url.ToString() })
    " class="btn btn-primary"
               role="button">
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
            </a>
        </p>
    </div>*@

    <!-- about section start -->
    <div class="about_section layout_padding">
        <div class="container">
            <div class="about_section_main">
                <div class="row">
                    <div class="col-md-6">
                        <div class="about_taital_main">
                            <h1 class="about_taital">Chi tiết sản phẩm</h1>
                            
                            <p class="about_text">
                                <div class="motasach" align="center">
                                    <p>
                                        @Html.Raw(Model.Description.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
                                    </p>
                                </div>

                            <p class="ngaycapnhat">Ngày cập nhật: @Html.FormatValue(@Model.Published, "{0:dd/MM/yyyy}")</p>
                            <p class="giaban">Giá bán:<span>@Html.FormatValue(@Model.Price, "{0:#,##0}") VNĐ</span></p>
                            <p class="addtocard">
                                <a href="@Url.Action("ThemGioHang","GioHang", new { ms = Model.BookID, url =Request.Url.ToString() })
    " class="btn btn-primary"
                                   role="button">
                                    <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                                </a>
                            </p>
                            </p>
                            <div class="readmore_bt"><a href="@Url.Action("Product", "SachOnline")">XEM SẢN PHẨM</a></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div><img src="~/Images/@Model.Images" alt="@Model.Title" class="image_3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- about section end -->
    

SachOnline/Views/SachOnline/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!-- customer section start -->
<div class="customer_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="customer_taital">LIÊN HỆ VỚI CHÚNG TÔI</h1>
            </div>
        </div>
        <div id="main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="client_section_2">
                        <div class="client_main">

                            <div class="client_right">
                                <h3 class="name_text">Số điện thoại</h3>
                                <p class="dolor_text">
                                    0965326842
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="client_section_2">
                        <div class="client_main">

                            <div class="client_right">
                                <h3 class="name_text">Email</h3>
                                <p class="dolor_text">
                                    kimquyen@gmail.com                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="client_section_2">
                        <div class="client_main">

                            <div class="client_right">
                                <h3 class="name_text">Trực tiếp tại:</h3>
                                <p class="dolor_text">

                                    HỆ THỐNG CỬA HÀNG TẠI TPHCM :<br />

                                    - 30/11A Bến Than, huyện Củ Chi, TPHCM .<br />

                                    - 216A Bình Mỹ, huyện Củ Chi, TPHCM .



                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>
</div>
<!-- customer section end -->

SachOnline/Views/SachOnline/Product.cshtml
@using SachOnline.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<Book>
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@helper Truncate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>...</text>
    }
}
<!-- product section start -->
<div class="product_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="product_taital">Sản phẩm</h1>
                <p class="product_text">"Chọn sự xuất sắc, không phải sự thông thường. Đồ của bạn không chỉ là sản phẩm, mà là câu chuyện của sự độc đáo và chất lượng"</p>
            </div>
        </div>
        <div class="product_section_2 layout_padding">
            <div class="row">
                @foreach (var sach in Model)
                {
                    <div class="col-lg-3 col-sm-6">
                        <div class="product_box">
                            <h4 class="bursh_text">@Truncate(@sach.Title, 16)</h4>

                            <img src="~/images/@sach.Images" class="image_1">
                            <div class="btn_main">
                                <div class="buy_bt">
                                    <ul>
                                        <li class="active"><a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.BookID })">Xem chi tiết</a></li>

                                    </ul>
                                </div>
                                <h3 class="price_text">@string.Format("{0:#,##0,0}", @sach.Price)</h3>đ
                            </div>
                        </div>
                    </div>
                }

            </div>
            @*<div class="seemore_bt"><a href="#">See More</a></div>*@
        </div>
    </div>
</div>
<!-- product section end -->
@*Tạo liên kết các trang*@

    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount<div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Product", new { page = page }))
    </div>
    <style>
        .MenuTrang {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 20px;
        }

        .pagination {
            display: flex;
            justify-content: center;
            list-style: none;
            padding: 0;
        }

            .pagination li {
                margin: 0 5px;
                padding: 5px 10px;
                background-color: #f4f4f4;
                border: 1px solid #ddd;
                border-radius: 3px;
            }

                .pagination li.active {
                    background-color: #337ab7;
                    color: #fff;
                }
    </style>

SachOnline/Views/SachOnline/SachTheoChuDe.cshtml
@using SachOnline.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<Book>

@{
    ViewBag.Title = "SachTheoChuDe";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";

}


<h2 style="text-align:center">Sách theo chủ đề</h2>


<hr>
<div class="row text-center">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <div class="thumbnail">
                <img src="~/Images/@sach.Images" alt="@sach.Title" class="img-responsive img-rounded imgbook" style="width:400px;">
                <div class="caption">
                    <h4 style="min-height:70px;">
                        <a href="@Url.Action("SachTheoChuDe", "SachOnline", new { iMaCD = sach.CategoryID })">@sach.Title</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("ChiTietSach", "SachOnline", new {  id= sach.BookID })" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>

    }
</div>



@*<nav class="text-center">


        <!-- Add class .pagination-lg for larger blocks or .pagination-sm for smaller blocks-->
        <ul class="pagination">

            <li>
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            <li class="active"><a href="#">1</a></li>
            <li> <a href="#">2</a></li>
            <li> <a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li class="disabled"><a href="#">5</a></li>
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>

                </a>
            </li>
        </ul>
    </nav>-->*@

SachOnline/Views/SachOnline/SachTheoNhaXuatBan.cshtml
@using SachOnline.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<Book>


@{
    ViewBag.Title = "SachTheoNhaXuatBan";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<style type="text/css">
    .imgbook {
        transition: all 1s ease-in;
        width: 202.5px !important;
        height: 253.13px !important;
    }

        .imgbook:hover {
            transform: scale(0.9);
            cursor: pointer;
        }
</style>
<h2 style="text-align:center">Sách theo Nhà Xuất Bản</h2>
<hr>
<div class="row text-center">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <div class="thumbnail">
                <img src="~/Images/@sach.Images" alt="@sach.Title" class="img-responsive img-rounded imgbook" style="width:400px;">
                <div class="caption">
                    <h4 style="min-height:70px;">
                        <a href="@Url.Action("SachTheoNhaXuatBan", "SachOnline", new { iMaNXB = sach.NhaXuatBanID })">@sach.Title</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.BookID })" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
@*Tạo liên kết các trang*@

Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("SachTheoNhaXuatBan", new { iMaNXB = ViewBag.NhaXuatBanID, page = page }))
</div>
<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }
</style>
@*<nav class="text-center">


    <!-- Add class .pagination-lg for larger blocks or .pagination-sm for smaller blocks-->
    <ul class="pagination">

        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>

        <li class="active"><a href="#">1</a></li>
        <li> <a href="#">2</a></li>
        <li> <a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li class="disabled"><a href="#">5</a></li>
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>

            </a>
        </li>
    </ul>
</nav>*@

SachOnline/Views/SachOnline/Timkiem.cshtml
@using SachOnline.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<Book>
@{
    ViewBag.Title = "Timkiem";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@helper Truncate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>...</text>
    }
}
<!-- product section start -->

<div class="product_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="product_taital">
                    @using (Html.BeginForm())
                    {
                        <p>
                            LOẠI SẢN PHẨM: @Html.TextBox("SearchString") <input type="submit" value="Tìm kiếm" />
                        </p>
                    }
                            </h1>
                <p class="product_text">Dưới đây là kết quả tìm kiếm</p>
            </div>
        </div>
        <div class="product_section_2 layout_padding">
            <div class="row">
                @foreach (var sach in Model)
                {
                    <div class="col-lg-3 col-sm-6">
                        <div class="product_box">
                            <h4 class="bursh_text">@Truncate(@sach.Title, 16)</h4>

                            <img src="~/images/@sach.Images" class="image_1">
                            <div class="btn_main">
                                <div class="buy_bt">
                                    <ul>
                                        <li class="active"><a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.BookID })">Xem chi tiết</a></li>

                                    </ul>
                                </div>
                                <h3 class="price_text">@string.Format("{0:#,##0,0}", @sach.Price)</h3>đ
                            </div>
                        </div>
                    </div>
                }

            </div>
            @*<div class="seemore_bt"><a href="#">See More</a></div>*@
        </div>
    </div>
</div>
<!-- product section end -->
@*Tạo liên kết các trang*@

    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount<div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Timkiem", new { page = page }))
    </div>
    <style>
        .MenuTrang {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 20px;
        }

        .pagination {
            display: flex;
            justify-content: center;
            list-style: none;
            padding: 0;
        }

            .pagination li {
                margin: 0 5px;
                padding: 5px 10px;
                background-color: #f4f4f4;
                border: 1px solid #ddd;
                border-radius: 3px;
            }

                .pagination li.active {
                    background-color: #337ab7;
                    color: #fff;
                }
    </style>

SachOnline/Views/SachOnline/XacNhanMuaLai.cshtml
@{
    ViewBag.Title = "XacNhanMuaLai";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="about_section layout_padding">
    <div class="container">
        <div class="about_section_main">
            <div class="row">
                <div class="col-md-6">
                    <div class="about_taital_main">
                        <h1 class="about_taital">XÁC NHẬN ĐƠN HÀNG</h1>
                        <p class="about_text">Đơn hàng của quý khách đã được chúng tôi ghi nhận, chúng tôi sẽ liên hệ đến quý khách trong thời gian sớm nhất và giao hàng đúng hẹn</p>
                        <div class="readmore_bt">
                            @Html.ActionLink("VỀ TRANG CHỦ", "Index", "SachOnline")
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div><img src="~/images/Giaohang1.png" class="image_3"></div>
                </div>
            </div>
        </div>
    </div>
</div>

SachOnline/Views/SachOnline/chudecss.cshtml
@using SachOnline.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<Book>
@{
    ViewBag.Title = "chudecss";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@helper Truncate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>...</text>
    }
}
<!-- product section start -->
<div class="product_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="product_taital">Bộ sưu tập</h1>
                <p class="product_text">---------------------------------------------------------</p>
                @foreach (var bosuutap in Model)
                {
                    <p class="product_taital">@bosuutap.Category.CategoryName</p>
                    break;
                }
            </div>
        </div>
        <div class="product_section_2 layout_padding">
            <div class="row">
                @foreach (var sach in Model)
                {
                    <div class="col-lg-3 col-sm-6">
                        <div class="product_box">
                            <h4 class="bursh_text"> @Truncate(@sach.Title, 16)</h4>

                            <img src="~/Images/@sach.Images" class="image_1">
                            <div class="btn_main">
                                <div class="buy_bt">
                                    <ul>
                                        <li class="active"><a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.BookID })">Buy Now</a></li>

                                    </ul>
                                </div>
                                <h3 class="price_text"> @string.Format("{0:#,##0,0}", @sach.Price)</h3>
                            </div>


                        </div>
                    </div>
                }

            </div>
            <div class="seemore_bt"><a href="#">See More</a></div>
        </div>
    </div>
</div>
<!-- product section end -->
@*Tạo liên kết các trang*@

Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("chudecss", new { iMaCD= ViewBag.CategoryID, page = page }))
</div>
<style>
    .MenuTrang {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 20px;
    }

    .pagination {
        display: flex;
        justify-content: center;
        list-style: none;
        padding: 0;
    }

        .pagination li {
            margin: 0 5px;
            padding: 5px 10px;
            background-color: #f4f4f4;
            border: 1px solid #ddd;
            border-radius: 3px;
        }

            .pagination li.active {
                background-color: #337ab7;
                color: #fff;
            }
</style>