SachOnline/Areas/Admin/Controllers/DonHangQTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace SachOnline.Areas.Admin.Controllers
{
    public class DonHangQTController : Controller
    {
        // GET: Admin/DonHangQT
        dbSachOnlineDataContext db = new dbSachOnlineDataContext();
        // GET: Admin/DonHang
        public ActionResult Index(int? page)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")

            {
                return RedirectToAction("Login", "Home");

            }
            int iPageNum = page ?? 1;
            int iPageSize = 7;

            var ketqua = (from ctdh in db.CHITIETDATHANGs
                          join ctdhdh in db.DONDATHANGs on ctdh.MaDonHang equals ctdhdh.MaDonHang
                          join kh in db.KHACHHANGs on ctdhdh.MaKH equals kh.MaKH
                          join ms in db.Books on ctdh.BookID equals ms.BookID
                          select new donhang
                          {
                              MaDonHang = ctdh.MaDonHang,
                              MaKH = ctdhdh.MaKH,
                              HoTen = kh.HoTen,

                              Ngaydat = ctdhdh.Ngaydat,
                              Ngaygiao = ctdhdh.Ngaygiao,
                              Soluong = ctdh.Soluong,
                              BookID = ms.BookID,
                              Title = ms.Title,
                              Dongia = ctdh.Dongia
                          }).OrderBy(d => d.MaDonHang).ToPagedList(iPageNum, iPageSize);

            return View(ketqua);
        }


        public ActionResult Kimquyen()
        {
            var ketqua = (from ctdh in db.CHITIETDATHANGs
                          join ctdhdh in db.DONDATHANGs
                          on ctdh.MaDonHang equals ctdhdh.MaDonHang
                          join kh in db.KHACHHANGs
                          on ctdhdh.MaKH equals kh.MaKH
                          select new donhang
                          {
                              MaDonHang = ctdh.MaDonHang,
                              MaKH = ctdhdh.MaKH,
                              HoTen = kh.HoTen,
                              Ngaydat = ctdhdh.Ngaydat,
                              Ngaygiao = ctdhdh.Ngaygiao,
                              Soluong = ctdh.Soluong,
                              Dongia = ctdh.Dongia
                          }).ToList();


            return View(ketqua);

        }
        public ActionResult Details(int id)
        {
            var order = db.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == id);

            if (order == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            // Fetch details for the specific order
            var orderDetails = (from ctdh in db.CHITIETDATHANGs
                                join ctdhdh in db.DONDATHANGs on ctdh.MaDonHang equals ctdhdh.MaDonHang
                                join kh in db.KHACHHANGs on ctdhdh.MaKH equals kh.MaKH
                                join ms in db.Books on ctdh.BookID equals ms.BookID
                                where ctdh.MaDonHang == id
                                select new donhang
                                {
                                    MaDonHang = ctdh.MaDonHang,
                                    MaKH = ctdhdh.MaKH,
                                    HoTen = kh.HoTen,
                                    Ngaydat = ctdhdh.Ngaydat,
                                    Ngaygiao = ctdhdh.Ngaygiao,
                                    Soluong = ctdh.Soluong,
                                    BookID = ms.BookID,
                                    Title = ms.Title,
                                    Dongia = ctdh.Dongia
                                }).ToList();

            // Fetch customer name for the specific order
            var customerName = db.KHACHHANGs.Where(kh => kh.MaKH == order.MaKH).Select(kh => kh.HoTen).FirstOrDefault();

            // Pass the order, customer name, and order details to the view
            var viewModel = new OrderDetailsViewModel
            {
                Order = order,
                customerName = customerName,
                OrderDetails = orderDetails
            };

            return View(viewModel);
        }
        [HttpGet]
        public ActionResult Create()
        {
            // Assuming you want to create a new order with details based on an existing order
            // You need to provide the order ID for the existing order
            int existingOrderId = 1; // Change this to the ID of the existing order

            // Fetch the existing order
            var existingOrder = db.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == existingOrderId);

            if (existingOrder == null)
            {
                // Handle the case where the existing order is not found
                Response.StatusCode = 404;
                return null;
            }

            // Fetch details for the existing order
            var existingOrderDetails = (from ctdh in db.CHITIETDATHANGs
                                        join ms in db.Books on ctdh.BookID equals ms.BookID
                                        where ctdh.MaDonHang == existingOrderId
                                        select new donhang
                                        {
                                            MaDonHang = ctdh.MaDonHang,
                                            MaKH = existingOrder.MaKH,
                                            HoTen = existingOrder.KHACHHANG.HoTen, // Use navigation property
                                            Ngaydat = existingOrder.Ngaydat,
                                            Ngaygiao = existingOrder.Ngaygiao,
                                            Soluong = ctdh.Soluong,
                                            BookID = ms.BookID,
                                            Title = ms.Title,
                                            Dongia = ctdh.Dongia
                                        }).ToList();

            // Populate properties of the new order with details
            var newOrder = new DONDATHANG
            {
                Dathanhtoan = false, // Set default value, you may change this as needed
                Tinhtranggiaohang = 0, // Set default value, you may change this as needed
                Ngaydat = DateTime.Now, // Set default value, you may change this as needed
                Ngaygiao = DateTime.Now, // Set default value, you may change this as needed
                MaKH = existingOrder.MaKH // Use the customer ID from the existing order
            };

            // Pass the existing order, customer name, and order details to the view
            var viewModel = new OrderDetailsViewModel
            {
                Order = newOrder,
                customerName = existingOrder.KHACHHANG.HoTen,
                // Use navigation property
                OrderDetails = existingOrderDetails
            };

            // Provide dropdown lists or other necessary data for the view if needed
            ViewBag.Title = new SelectList(db.Books.ToList().OrderBy(n => n.Title), "BookID", "Title");

            ViewBag.HoTen = new SelectList(db.KHACHHANGs.ToList(), "MaKH", "HoTen");

            return View(viewModel);
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(OrderDetailsViewModel viewModel)
        {
            try
            {
                // Add the new order to the database
                db.DONDATHANGs.InsertOnSubmit(viewModel.Order);
                db.SubmitChanges();

                // Process order details and add them to the database
                foreach (var detail in viewModel.OrderDetails)
                {
                    // Create a new CHITIETDATHANG object and set its properties
                    var newDetail = new CHITIETDATHANG
                    {
                        // Explicitly convert nullable int? to int, providing a default value if MaDonHang is null
                        MaDonHang = viewModel.Order.MaDonHang, // Replace 0 with your desired default value
                        BookID = (int)detail.BookID,
                        Soluong = detail.Soluong,
                        Dongia = detail.Dongia
                    };

                    // Add the new detail to the database
                    db.CHITIETDATHANGs.InsertOnSubmit(newDetail);
                }

                // Submit changes to the database
                db.SubmitChanges();

                // Redirect to the list of orders
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Handle exceptions here
                // You may want to log the exception or show an error message
                return View(viewModel); // Return the view with the same data if an error occurs
            }
        }



        //[HttpGet]
        // public ActionResult Edit(int id)
        // {
        //    var order = db.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == id);


        //   if (order == null)
        //  {
        //       Response.StatusCode = 404;
        //      return null;
        //  }

        // Fetch details for the specific order
        //  var orderDetails = (from ctdh in db.CHITIETDATHANGs
        //          join ctdhdh in db.DONDATHANGs on ctdh.MaDonHang equals ctdhdh.MaDonHang
        //          join kh in db.KHACHHANGs on ctdhdh.MaKH equals kh.MaKH
        //          join ms in db.Books on ctdh.BookID equals ms.BookID
        //          where ctdh.MaDonHang == id
        //          select new donhang
        //         {
        //            MaDonHang = ctdh.MaDonHang,

SachOnline/Areas/Admin/Views/DonHangQT/Create.cshtml
@*@model SachOnline.Models.DONDATHANG*@
@using SachOnline.Models;
@using PagedList.Mvc;
@model SachOnline.Models.OrderDetailsViewModel

@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanTriVien.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>DONDATHANG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Order.Dathanhtoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order.Dathanhtoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Dathanhtoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order.Tinhtranggiaohang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order.Tinhtranggiaohang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Tinhtranggiaohang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order.Ngaydat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order.Ngaydat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Ngaydat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order.Ngaygiao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order.Ngaygiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Ngaygiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order.MaKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Order.MaKH, ViewBag.HoTen as SelectList, "Chọn khách hàng", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Order.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @*@Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Published, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>*@
            <label class="control-label col-md-2">So luong:</label>
            <div class="col-md-10">
                <input type="number" name="sSoluong" required />
            </div>
        </div>


        @*<div class="form-group">
                @Html.LabelFor(model => model.Order.BookID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Order.BookID, ViewBag.Title as SelectList, "Chọn sách", new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.Order.BookID, "", new { @class = "text-danger" })
                </div>
            </div>*@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SachOnline/Areas/Admin/Views/DonHangQT/Delete.cshtml
@model SachOnline.Models.DONDATHANG

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanTriVien.cshtml";
}

<h2>XÁC NHẬN THÔNG TIN CẦN XÓA</h2>

<h3>Bạn quyết định xóa đơn hàng này?</h3>
<h4>@Html.Raw(ViewBag.ThongBao) </h4>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Mã đơn hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDonHang)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Mã khách hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KHACHHANG.MaKH)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Tên khách hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KHACHHANG.HoTen)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Thanh toán:
        </dt>

        <dd>
            @{
                if (Model.Dathanhtoan == false)
                {
                    <span style="color: red;">Chưa thanh toán</span>
                }
                else
                {
                    <span style="color: green;">Đã thanh toán</span>
                }
            }
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Tình trạng giao:
        </dt>

        <dd>
            @{
                if (Model.Tinhtranggiaohang == 0)
                {
                    <span style="color: red;">Đang giao</span>
                }
                else
                {
                    <span style="color: green;">Đã giao</span>
                }
            }
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Ngày đặt:
        </dt>

        <dd>
            @Html.FormatValue(Model.Ngaydat, "{0:dd/MM/yyyy}")
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Ngày giao:
        </dt>

        <dd>
            @Html.FormatValue(Model.Ngaygiao, "{0:dd/MM/yyyy}")
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="XÓA" class="btn btn-default" /> |
            @Html.ActionLink("VỀ TRANG QUẢN LÝ ĐƠN HÀNG", "Index")
        </div>
    }
</div>

SachOnline/Areas/Admin/Views/DonHangQT/Details.cshtml
@*@model SachOnline.Models.DONDATHANG*@
@using SachOnline.Models;
@using PagedList.Mvc;
@model SachOnline.Models.OrderDetailsViewModel

@using PagedList;
@using PagedList.Mvc;


@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanTriVien.cshtml";
}

<h2>CHI TIẾT ĐƠN ĐẶT HÀNG</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Mã đơn hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.MaDonHang)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Mã khách hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.KHACHHANG.MaKH)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Tên khách hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.KHACHHANG.HoTen)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Thanh toán:
        </dt>

        <dd>
            @{
                if (Model.Order.Dathanhtoan == false)
                {
                    <span style="color: red;">Chưa thanh toán</span>
                }
                else
                {
                    <span style="color: green;">Đã thanh toán</span>
                }
            }
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Tình trạng giao:
        </dt>

        <dd>
            @{
                if (Model.Order.Tinhtranggiaohang == 1)
                {
                    <span style="color: red;">Đang giao</span>
                }
                else
                {
                    <span style="color: green;">Đã giao</span>
                }
            }
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Ngày đặt:
        </dt>

        <dd>
            @Html.FormatValue(Model.Order.Ngaydat, "{0:dd/MM/yyyy}")
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Title)*@
            Ngày giao:
        </dt>

        <dd>
            @Html.FormatValue(Model.Order.Ngaygiao, "{0:dd/MM/yyyy}")
        </dd>
        <dt>
            Số lượng:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>
        <dt>
            Mã sách:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDetails.FirstOrDefault().BookID)
        </dd>
        <dt>
            Tên sách:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDetails.FirstOrDefault().Title)
        </dd>
        <dt>
            Đơn giá:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dongia)
        </dd>

    </dl>
</div>


<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Order.MaDonHang }) |
    @Html.ActionLink("VỀ TRANG QUẢN LÝ ĐƠN HÀNG", "Index")
</p>

SachOnline/Areas/Admin/Views/DonHangQT/Edit.cshtml
@model SachOnline.Models.DONDATHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanTriVien.cshtml";
}

<h2>ĐIỀU CHỈNH THÔNG TIN ĐƠN HÀNG</h2>
@*Thêm thuộc tính cho form để upload ảnh*@
@using (Html.BeginForm("Edit", "DonHangQT", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.BookID)*@

        <div class="form-group">
            @*    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })*@

            <label class="control-label col-md-2">Mã đơn hàng:</label>

            <div class="col-md-10">
                @*Chỉ hiển thị mã sách không cho sửa*@
                @*@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })*@
                <input type="text" size="70" name="iMaDonHang" value="@Model.MaDonHang" readonly />

            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Đã thanh toán:</label>
            <div class="col-md-10">
                <label class="radio-inline">
                    <input type="radio" name="iDathanhtoan" value="true" @(Model.Dathanhtoan ) /> Đã thanh toán
                </label>
                <label class="radio-inline">
                    <input type="radio" name="iDathanhtoan" value="false" @(!Model.Dathanhtoan) /> Chưa thanh toán
                </label>
            </div>
        </div>


        <div class="form-group">

            <label class="control-label col-md-2">Tình trạng giao hàng:</label>
            <div class="col-md-10">

                <input type="text" size="70" name="iTinhtranggiaohang" value="@Model.Tinhtranggiaohang" required />   Điền 0 nếu đã giao hàng, 1 nếu chưa giao hàng

            </div>
        </div>


        <div class="form-group">
            @*@Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Published, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>*@
            <label class="control-label col-md-2">Ngày đặt:</label>
            <div class="col-md-10">
                <input type="datetime" name="iNgaydat" required value="@Convert.ToDateTime(Model.Ngaydat)" />
            </div>
        </div>
        <div class="form-group">
            @*@Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Published, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>*@
            <label class="control-label col-md-2">Ngày giao:</label>
            <div class="col-md-10">
                <input type="datetime" name="iNgaygiao" required value="@Convert.ToDateTime(Model.Ngaygiao)" />
            </div>
        </div>



        @* <div class="form-group">
                <label class="control-label col-md-2">Tên khách hàng:</label>
                <div class="col-md-10">

                    <input type="text" size="70" name="iMaKH" value="@Model.MaKH" required />

                </div>
            </div>*@



        <div class="form-group">
            @*@Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                </div>*@
            <label class="control-label col-md-2">Tên khách hàng:</label>
            <div class="col-md-10">
                @*Hiển thị ViewBag.MaCD vào dropdownlist*@
                @Html.DropDownList("MaKH")
            </div>
        </div>









        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="LƯU THÔNG TIN" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("VỀ TRANG QUẢN LÝ ĐƠN HÀNG", "Index")
</div>

SachOnline/Areas/Admin/Views/DonHangQT/Index.cshtml
@*Khai bao su dung chuc nang phan trang*@
@using SachOnline.Models;
@using PagedList.Mvc;
@*@model IEnumerable<SachOnline.Models.Book>*@
@*@model PagedList.PagedList<SachOnline.Models.DONDATHANG>*@
@model PagedList.PagedList<SachOnline.Models.donhang>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanTriVien.cshtml";
}

<h2 style="text-align:center">QUẢN LÝ THÔNG TIN ĐƠN HÀNG</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Images)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Published)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NhaXuatBanID)
            </th>
            <th></th>*@

        <th style="text-align:center;width:140px">
            Mã đơn hàng
        </th>
        <th style="text-align:center;width:200px">
            Tên khách hàng
        </th>
        @*<th style="text-align:center;width:200px">
                Thanh toán
            </th>
            <th style="text-align:center;width:200px">
                Tình trạng giao
            </th>*@
        <th style="text-align:center;width:200px">
            Ngày đặt
        </th>
        <th style="text-align:center;width:200px">
            Ngày giao
        </th>

        <th style="text-align:center;width:80px">
            Số lượng
        </th>
        <th style="text-align:center;width:80px">
            Mã sách
        </th>
        <th style="text-align:center;width:80px">
            Tên sách
        </th>
        <th style="text-align:center;width:80px">
            Tổng tiền
        </th>

        <th style="text-align:center"></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDonHang)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)

            </td>


            @*<td>
                    @{
                        if (item.Dathanhtoan == false)
                        {
                            <span style="color: red;">Chưa thanh toán</span>
                        }
                        else
                        {
                            <span style="color: green;">Đã thanh toán</span>
                        }
                    }
                </td>
                <td>
                    @{
                        if (item.Tinhtranggiaohang1 == 1)
                        {
                            <span style="color: red;">Đang giao</span>
                        }
                        else
                        {
                            <span style="color: green;">Đã giao</span>
                        }
                    }
                </td>
            *@

            <td>
                @*Định dạng hiển thị*@
                @*@Html.DisplayFor(modelItem => item.Published)*@
                @Html.FormatValue(item.Ngaydat, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @*Định dạng hiển thị*@
                @*@Html.DisplayFor(modelItem => item.Published)*@
                @Html.FormatValue(item.Ngaygiao, "{0:dd/MM/yyyy}")
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Soluong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dongia)
            </td>

            @*
                <td>
                @Html.DisplayFor(modelItem => item.Price)
                @Html.FormatValue(item.Price, "{0:#,##0}")
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.KHACHHANG.HoTen)
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.NhaXuatBan.NhaXuatBanName)
                </td>*@

            <td>
                <a href="@Url.Action("Edit", new { id=item.MaDonHang })" class="btn btn-warning" role="button">Sửa</a>
                <a href="@Url.Action("Details", new { id=item.MaDonHang })" class="btn btn-primary" role="button">Chi tiết</a>
                <a href="@Url.Action("Delete", new { id=item.MaDonHang })" class="btn btn-danger" role="button">Xóa</a>

            </td>
        </tr>
    }

</table>
@*Tạo liên kết phần trang*@
    Trang @(Model.PageCount<Model.PageNumber ?0: Model.PageNumber)/@Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .MenuTrang {
            display: inline;
            text-align: center;
        }
@*<div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>*@



    </style>